name: Cron Jobs Planifi√©s

on:
  schedule:
    - cron: '0 0 * * *'       # Tous les jours √† minuit (UTC)
    - cron: '0 0 * * 1'       # Tous les lundis √† minuit (UTC)
    - cron: '0 0 1 * *'       # Le 1er de chaque mois √† minuit (UTC)

jobs:
  debut_jour:
    if: github.event.schedule == '0 0 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: T√¢che quotidienne
        run: echo " D√©but d'une nouvelle journ√©e !"

  debut_semaine:
    if: github.event.schedule == '0 0 * * 1'
    runs-on: ubuntu-latest
    steps:
      - name: T√¢che hebdomadaire
        run: echo " D√©but d'une nouvelle semaine !"

  debut_mois:
    if: github.event.schedule == '0 0 1 * *'
    runs-on: ubuntu-latest
    steps:
      - name: T√¢che mensuelle
        run: echo "üóìÔ∏è D√©but d'un nouveau mois !"
